version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ortahisar_genckart_db
    restart: always
    environment:
      POSTGRES_USER: genckart_user
      POSTGRES_PASSWORD: genckart_password
      POSTGRES_DB: ortahisar_genckart_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: ortahisar_genckart_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
